2021-03-03 18:38:26,436 ERROR: Exception on /reset_password_request [GET] [in c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sebid\flaskMegaTutorial\app\routes.py", line 276, in reset_password_request
    form = ResetPAsswordRequestForm()
NameError: name 'ResetPAsswordRequestForm' is not defined
2021-03-03 18:38:54,057 INFO: Microblog startup [in C:\Users\sebid\flaskMegaTutorial\app\__init__.py:84]
2021-03-03 18:39:15,762 ERROR: Exception on /reset_password_request [POST] [in c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sebid\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sebid\flaskMegaTutorial\app\routes.py", line 283, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\sebid\flaskMegaTutorial\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\sebid\flaskMegaTutorial\app\models.py", line 116, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'self' is not defined
